Fix unit conversions warning
traitecoevo/traits.build pull request #100
Opened 2023-10-19 00:09 UTC by yangsophieee

The unit conversions warning (#65) was showing up again for both @ehwenk and me. It seems to me that there was something going on with the `mutate` `ifelse` statement not being vectorised in the expected way. I don't fully understand why it wasn't working as expected (because it should've been) but after several hours of testing I've just decided to accept that adding `rowwise` works and produces the expected output.

The problem dataset was once again, vanderMoezel_1987.

2023-10-19 10:46 UTC, dfalster commented
I'll take a look at this before merging

2023-10-19 22:23 UTC, dfalster commented on R/process.R
>      dplyr::group_by(.data$ucn, .data$to_convert) %>%
need to add value_type to group_by call,  ie

```
dplyr::group_by(.data$ucn, .data$to_convert, .data$value_type)
```

2023-10-19 22:27 UTC, dfalster requested changes
I looked into this. The issue can be resolved by adding value_type into the group_by statement. 

When I checked what was happening inside the functions `f_standard` binned data was still being fed into this. Adding value_type into the group_by fixes this. 

This is preferable to rowwise, as rowdies will result in more function calls

2023-10-19 22:27 UTC, dfalster commented on R/process.R
> +    dplyr::rowwise() %>%
move rowwise as will make everything much slower

2023-10-19 22:27 UTC, dfalster commented on R/process.R
>      dplyr::group_by(.data$ucn, .data$to_convert) %>%
need to add value_type to group_by call,  ie

```
dplyr::group_by(.data$ucn, .data$to_convert, .data$value_type)
```

2023-10-19 22:30 UTC, yangsophieee commented
@dfalster Thanks Dan!!! I was wondering what debugging tools you used to look into what was being fed into the functions? I struggle with loops where only one particular iteration throws a warning.

2023-10-19 22:35 UTC, dfalster commented
In this case I put a browser() call first in `process_unti_conversions`, then also in `f_standard` -- with the latter I was able to check the values being called within `f_standard` , which is when I saw values that were bins and shouldn't be there. 

This would cause lots of browser calls, so I only ran this specifically on the problem study: vanderMoezel_1987

2023-10-19 22:37 UTC, yangsophieee commented
Oh ok! I did do that and saw the bins getting read in but I thought the ifelse function would only run f_standard on the ones that aren't bins.

2023-10-19 22:42 UTC, dfalster commented
me too. hence why I double checked with a browser within `f_standard`

2023-10-20 01:59 UTC, yangsophieee commented
@dfalster Changes have been implemented! Thank you :)

2023-10-20 02:17 UTC, dfalster approved these changes

2023-10-20 04:58 UTC, merged